# Define package for modeling
[project]
name = "modeling-5632425"
description = "Hyperparameter optimization and validation tools"
authors = [{ name = "Katsiaryna", email = "katsiaryna.shymchonak@innowise.com" }]
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["hyperopt", "optuna", "numpy", "pandas", "dill", "scikit-learn"]

[tool.poetry.plugins."poetry.dynamic-versioning"]
"poetry-dynamic-versioning" = "poetry_dynamic_versioning.plugin"

[tool.dynamic-versioning]
enable = true
vcs = "git"
style = "pep440"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["modeling*"]
