name: Publish multiple packages to PyPI

on:
  push:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Debug workspace
        run: |
          echo "Current directory: $(pwd)"
          ls -R

      - name: Install Poetry
        run: pip install poetry

      - name: Publish feature_engineering package
        working-directory: pipe/src/feature_engineering
        run:
          poetry publish --build
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_API_TOKEN }}

      - name: Publish modeling package
        working-directory: pipe/src/modeling
        run:
          poetry publish --build
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_API_TOKEN }}
